[hydro]
system = "relativistic"
gamma_law_index = 1.333

[model]
setup = "jet_in_cloud"
launch_radius = 1e8
cloud_mass = 1e32
engine_delay = 1.0
engine_duration = 1.0
engine_strength = 1.0
engine_theta = 0.1
engine_u = 30.0
envelop_mass = 1e30
psi = 0.25
u_min = 0.1

[mesh]
inner_radius = 1e8
outer_radius = 3e10
num_polar_zones = 1024
block_size = 32

[control]
final_time = 1.0
start_time = 1.0
checkpoint_interval = 1.0
products_interval = 1.0
