[hydro]
type = "relativistic"
gamma_law_index = 1.333

[model]
type = "jet_in_cloud"
engine_duration = 1.0
engine_strength = 1.0

[mesh]
inner_radius = 1.0
outer_radius = 1e6
num_polar_zones = 128
block_size = 32

[control]
final_time = 1.0
checkpoint_interval = 1.0
products_interval = 1.0
